spring:
  application:
    name: gachipay

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/gachipay?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sherlock

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile